[book]
authors = ["me2seeks"]
language = "en"
multilingual = false
src = "src"
title = "Me2seeks Blog"

[output.html]
additional-css = ["theme/style3.css"]
additional-js = ["assets/custom.js", "assets/bigPicture.js"]
git-repository-url = "https://github.com/me2seeks/me2seeks.github.io"
edit-url-template = "https://github.com/me2seeks/me2seeks.github.io/edit/main/{path}"

[output.html.fold]
enable = true
level = 1

# [output.katex]

# [preprocessor.katex]
